authdb:
  image: mysql:5.6.25
  env_file:
    - .env.database
authweb:
  image: gobliip/auth-server:0.0.1-RELEASE
  ports:
    - "5021:5021"
  expose:
    - "5021"
  links:
    - authdb
  external_links:
    - eureka
  env_file:
    - .env.database
    - .env